name: Feature Branch

on:
  push:
    branches: [ master ]
    
      

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: change directory 
        run: cd Sep_project7y7
      - name: testing maven function 
        run: mvn -B verify --file pom.xml 

    
